const blog = {
  img: "",
  title: "",
  subtitle: "",
  body: ``,
};

const blogs = [
  {
    img: "https://i.ibb.co/PT0G9HK/DH-banner-image.png",
    title: "What is the Digital Humanities?",
    subtitle: "Something Old, New, Borrowed, & True",
    body: `\tThe discussion in class seemed to focus on the digital humanities to be something emerging, and forward looking and focused. The professor pushed back on these perhaps common preconceptions and offered an interesting perspective on how we might think that digital humanities are actually much older, and less easy to distinguish from the Humanities conventionally understood. The process of representing and manifesting personal vision onto the world through creating holistic integrated aesthetic experiences stretches back perhaps even to pre-history with the setting up of sacred spaces through a mixture of art work and playing with light. 
 
    \tThe discussion reminds me of the discussion of computation and its novelty engendered by the advent of cognitive science--a field that focused much of its attention on the analogy of human cognitive processes to computer systems. This inverts the common intuition that computational systems are a novel technology--rather than a continuation of the basic processes that undergird our own cognitive processes and the project to outsource and supplement our own computational activities through the advancement of technology.
     
    \tI see a similar analogy between the computer science field of informatics and the humanities that may bear fruit in the humanities, which I call cultural informatics. Informatics is the science of data storage and retrieval--including the representation, processing and communication of information in computational systems. These focus points, just as they are pressing and salient in the investigation of individual cognitive processes, are also central to the study of the humanities, and the transmission of a cultural heritage of information across generations. It leads me to wonder to what extent a civilization--understood as a collection of cities and states all participating in a common cultural identity--might be a computational system for the maintenance and development of the information making up said culture. These thoughts are very premature and underdeveloped at this time, but seeing how much fruit has been born by exploring a theoretical bridge between informatics and psychology through cognitive science, makes me curious as to whether the same may come to pass between informatics and the humanities through the digital humanities.
     
    \tIn some ways my perspective on the digital humanities has remained the same as when I first chose the specialization back last year. I have seen a technological shift across almost every major industry--particularly those heavily focused on information services--that has led to a split in those industries between established players made arrogant by their institutional entrenchment and near mythological cultural status--and innovative upstarts that lack relative credibility, resources and status, but nonetheless come to replace the old guard by forseeing the coming change and ensuring they are ready for it when it inevitably crashes forth. `,
  },

  {
    img: "https://i.ibb.co/T1dY4g4/facilities-infrastructure-20-Social-and-cultural-informatics-platform-SCIP-banner.jpg",
    title: "Coding & Culture",
    subtitle: "The Digital Humanities as a Cultural Informatics",
    body: `\tThis week, continuing the theme from the previous one, the class explored the ways in which the digital humanities may not be as new as it might appear to be--through a historical examination of code. We discussed the example of the Rosetta Stone, a means of deciphering across different predominant languages in antiquity. We also discussed the I Ching, an ancient Chinese book of ethics to guide people in personal decision making. This made me think again of my conception of cultural informatics from the previous week. Technology seems like a way to maintain cultural integrity and persistence across generations by outsourcing the temporal and limited computational, representational, and communicative powers of individual people to devices more able to persist across time and retain information in a constant form. 
 
    This process still of course requires individual feedback in the form of interpreting and updating technologies such as the I Ching--and in some sense we might think of these schools and institutions that keep the “spirit” or meaning of these texts alive over time as transpilers (to use an analogy to a coding technology) which update the language through which code is expressed, and the conventions through which they are interpreted, to ensure they work in reliable and consistent ways as programming languages and undergirding technologies change. 
     
    This makes sense, as was discussed in class, the reading of the I Ching to guide personal decisions was often guided by an oracle, who might be able to be thought of as acting as a transpiler--dynamically interpreting the code to the different compilers (people) that were trying to read it to get to the same result (action in accordance with the ethical principles of the I Ching) in different cases (applied to different individual decision contexts).`,
  },
  {
    img: "https://i.ibb.co/BZGfTCL/2017-09-07-The-Philosophy-of-Writing-Image.jpg",
    title: "argue.js",
    subtitle: "Philosophy & the Digital Humanities",
    body: `\tThis week I gave my module presentation on argue.js, a web app I made to explore the connections between philosophy and digital technology--both pedagogically and conceptually. Philosophy has always placed a significant focus on dialectic and the harmony between words and deeds--that is to say, always engaging in continual attempts to apply understanding and receiving feedback as a way to refine and advance insights. Digital technology offers a unique advantage over the text in that it can respond dynamically to user feedback, and also offer opportunities for the user to interact directly with what they are attending to. I applied this in two ways: a multiple choice test and a code-to-argument transpiler. The multiple choice test was given some personality by making it be delivered by a NPC Socrates--and the test integrates well with the reading experience, allowing users to get immediate and direct feedback on their retention to identify what they have achieved and narrow in on what they have left to master as they are going through the text.
 
    The transpiler allows users to directly play with and make use of the ideas taught in the lesson through the app. The lesson was one about argument theory and javascript--but the deeper lesson trying to be conveyed was one about logical realism--taking seriously the existence of logical rules which structure our representations of the world and imbue them with an ordered meaning. This was demonstrated implicitly by walking users through a process in which an argument of a standard type, the syllogism, relayed in plain English, was translated into Javascript code while retaining the same identifiable logical format. The grand finale of this lesson was the aforementioned transpiler, which after telling the student about how the same logical structure underlaid both argument and code, allowed them to see it for themselves by playing with and altering the code and generating new arguments out of that code.
     
    In this way I see digital technology as useful to teaching philosophy at both a surface level--allowing the use of more tools and a more seamless integration of tools in one learning environment--and at a deeper level, allowing for students to observe principles of logic at work through interactive exercises that do more than assess or refine understanding, but build on it too.`,
  },
  {
    img: "https://i.ibb.co/nM2Lypt/digital-media-blog.png",
    title: "The Digital Text",
    subtitle: `Looking Back to Plato's <span class="italics">Phaedrus</span>`,
    body: `\tI want to center this entry on the criticism found in <span class="italics">In the Event of a Variable Text</span> of Socrates’ criticism of the written word in Plato’s <span class="italics">Phaedrus</span>. This is the crux of my MA thesis research, so it struck me. The paper resisted the criticism of the written text and proposed instead that the text, especially through digital technology, is capable of variability--of dynamic, active responsiveness and assertiveness. This is a thesis I generally agree with, however, it was the criticism of the Phaedrus which I found lacking--as it missed the central point of that criticism of the written word, namely, that it was communicated through the written word. As a fan of the conversational word over the static written word, Plato did not write his dialogues to give out answers to state his positions directly, but rather, they are written as dialogues between characters, and Plato is not one of these characters. 
 
    What I am getting at here is not mere sophistry to defend Plato, but more, to argue that the central thesis of this work is actually a continuation of Plato’s very project to improve the text by engaging with it as a variable medium from both the standpoint of the writer and the reader. Because of the dialogic format of Plato’s works, and the lack of a narrator to declare a victor of an argument--it is left to the reader to interpret and discern both the beliefs of the author, and the truth of the positions put forward. In this was the text of the dialogue is designed in such a way that forces the reader to engage with the text as unfixed and variable, something which is not set, but happening, and which they must actively participate in to discern the meaning of. In this way I believe Plato’s dialogues are actually the starting point of and a key to the project of the author in <span class="italics">In the Event of A Variable Text</span>.`,
  },
  {
    img: "https://i.ibb.co/875pjcB/Dublin-City-Paratext-vs-Text2-600x315-1.jpg",
    title: "The Multimodal Text",
    subtitle: "Using Salience & Framing to Overcome Information Entropy",
    body: `\tIn this post I want to explore the following claim in the paper <span class="italics">The Compelling Nature of Transmedia Storytelling</span>, “With multimodal texts, reading complexity encompasses more than just language structure. The entire information structure of the text must be taken into account” (pg. 218). I was particularly interested in this because it related back to what I am attempting to achieve with my project argue.js--to create a digital multimodal text in which the lesson is not delivered through language alone, but through the entire structure of the app with which the user interacts--including their visual perception and their idiosyncratic creative decision making--through the way the structure of the app conditions and interacts with these personal. The author identifies as significant the information value, salience, and framing of the medium. I want to focus on discussing salience and framing. Salience is “the degree by which a modal element draws attention to itself” (pg. 218) and framing as conveying meaning through composition and rhythm of the experience laid out by the medium.
 
    One unique advantage digital texts have to offer is a new level of weaving together the elements of salience and framing--to draw attention to itself and its information content through the composition of the medium to overcome what the author identifies as “information entropy” (pg. 218) -- the degree of unpredictability in an information structure. When encountering information about an unfamiliar subject, the relation of the information about that subject is unknown, and thus will be unpredictable--such that how the information being presented fits together or relates to the subject will appear more complex and less digestible. The inclusion of interactive, visual and creatively stimulating features, such as the Transpiler in argue.js aimed to be, offer a means to overcome that, as they are a means of narrowing salience (attention) of the user and framing the information received in relation to a defined system that they can use to tie together the disparate information they have just processed through playing around with to create novel arguments (again in the case of argue.js). Later in the paper the author discussed how the incorporation of these elements in a medium can be useful to pedagogy in making students “co-creators during meaning making” (pg. 224). Insofar as we make meaning by coming to an understanding of how different points of information relate to one another in the context of a larger lesson or subject, this can be informative in conceptualizing the aim of the experiment of argue.js, and in doing so provide greater clarity to the project and its potential.`,
  },
  {
    img: "https://i.ibb.co/3Rxm62p/download-2.jpg",
    title: "Ludonarrative Dissonance",
    subtitle: "Exploring the Distinction Between Procedure & Narrative",
    body: `\tI wanted to take the opportunity of this week’s blog topic to discuss something which has recently become very relevant to my research--the concept of ludonarrative dissonance--the harmony between gameplay and game plot. The discussions this and last week in class have seemed to relate heavily to this idea, in discussing the interplay between a story and the procedures through which it is communicated--digital or analog, interactive or passive and so on. This has got me thinking, and relating it back to the paper a few weeks back on the variability of the written word, where precisely is the line demarcating where the gameplay or procedures end and the content of a narrative begin? This question, and the concept of ludonarrative dissonance reminds me of the idea of being hypocritical--doing one thing but saying another which contradicts it. 
 
    There seems to be an idea, and at least to me it seems intuitive, that words and actions can contradict one another--and this seems to be the core idea of ludonarrative dissonance. It seems that the way we present ourselves to other people through the way that we act tells a story about who we are. Likewise it seems that the procedures through which a story is told tells us something about the character and intention of that story--perhaps about the story behind the story, of its author and how they wanted us to interpret it. I think for this reason, that stories involving extensive action are best conveyed by video games, because this is a medium which requires action from the user in order to engage in it. These thoughts need more development, but this has been useful to start to think through them.`,
  },
  {
    img: "https://i.ibb.co/1GSNc30/img-170999-augmentedreality-bg.jpg",
    title: "Virtual Reality",
    subtitle: "Critique: Not Quite There Yet",
    body: `\tThis week featured an exploration of some different virtual reality platforms such as Virbela and some user created spaces on Mozilla Hubs. This experience largely confirmed my previous thoughts on VR, that the technology is very much in its early stages, and as of yet, not particularly useful for practical purposes. Zoom or an in person meeting is a significantly better social experience for allowing one to see each other’s facial expressions and reduce the amount of distractions on screen not relevant to the meeting at hand. In terms of being able to interact with others in a digital space, video games seem to offer a much better casual social experience, allowing the same voice and text communications but also offering more engaging and interesting things to do together in a digital space. Virbella struck me as similar to an MMO like World of Warcraft with the aesthetic of an office space and all the gamified elements stripped from it.
 
    In terms of the pedagogical sea life VR experience we tried out in class, it was also lackluster in terms of practicality--seeming a poor substitute to a classroom or video. As a proof of concept of course, these technologies are incredibly interesting and hold great promise--making them worth learning and creating with today--but seem unable to deliver just yet anything that makes them the better alternative in professional and educational contexts.`,
  },
  {
    img: "https://i.ibb.co/sv4wkxy/IMG-5724.jpg",
    title: "Media Archaeology",
    subtitle: "Obselence & Technology Lost to History",
    body: `\tThis week we explored an interesting paradox--the means of recording information have never been so accessible or ubiquitous--and yet the rate at which we are losing, potentially irretrievably, the digital artifacts of our time is unprecedented. As the hardware and software through which applications which have shaped and which speak to particular moments in the development of digital culture and technology change, these applications become inaccessible--requiring extensive efforts in constructing emulators to execute. It is easy to take software for granted since it is easily stored, but as we lose the technology which ran that software, and the know-how to replicate that technology--we risk losing key cultural artifacts and creating a gaping hole for future historians and archivists in making sense of this moment in our culture.
 
    Beyond purely epistemic concerns, this may have terrible practical consequences as well. Psychologists and designers will lose out on key pieces in the development of interfaces and human computer interaction design which if understood as a whole could reveal something to us about our nature and the trajectory of progress among interfaces. The loss of this information stands to deprive us, even within our lifespans, of a history that could reveal to us more about the kind of creatures we are, and the history of interface aesthetics that could inform and provide a wellspring of ideas to designers of the future. 
     
    The central issue seems to be at the crossroads of the incredible pace of technological development and the lack of financial incentive to maintain the infrastructure necessary to keep obsolete technologies operational and accessible for research and private interest. The process of maintaining these technologies in such a state, and ensuring that moving forward would be expensive and both labor and resource intensive. Yet profit and progress, at least in the short term, is to be found in what is next, not what has come before. At the same time many great archival projects are expensive and difficult, perhaps the imperative is for those passionate about history and the digital humanities to reach out to conventional sources of funding and resources for archival preservation and persuasively make the case that digital technologies of the recent past, and those soon to become obsolete in the present, are deserving of the resources required to keep them alive.`,
  },
  {
    img: "https://i.ibb.co/nCjnt7v/1-WVe-H8o-EAek-Lw7x1e7f-BWFA.jpg",
    title: "User Interface Design",
    subtitle: "A Quintessentially Digital Humanities Field of Aesthetics",
    body: `\tThis week we discussed user interface design and traced back the history of user interfaces back to the 1970s. What struck me as odd was how similar the user interface for a desktop has remained with the windowed design, bottom taskbar, cursor and other such basic features. The direction since the inception of these tools has seemed less like paradigm shifting redesigns, and more like the reduction and simplification of these interfaces away from text and towards icons. Perhaps the touchscreen was the biggest shift in UI design, but even then, looking back at the IPhone, the basic idea of a taskbar at the bottom of the screen, shortcut icons, which when clicked reveal windows has remained largely the same in concept--if totally revolutionized in execution. 
 
    This has led me to consider User Interface from the standpoint of the philosophy of aesthetics--in which one of the most enduring and contentious debates is around whether there are universal principles of aesthetic design. In many ways what we do when we set out to create a user interface is to emulate the operation of our own mind--in simplifying the world into a set of representations that can be meaningfully interpreted quickly and intuitively and disclose to the subject the salience or importance of what they are looking at. If we accept this view of perception and basic cognition as plausible, then it may serve two functions--a way of explaining the persistence of the basic model of UI design we see today, and situate the digital humanities within the wider humanities--suggesting that it is less new than it may intuitively seem to be. 
     
    It would be an interesting project to try to build off contemporary literature philosophy of aesthetics to develop a scholarly approach to aesthetic criticism relating to UI design. This may reveal more about what this new aesthetic form can reveal to us about the human condition and create a mutually constructive feedback loop with practical UI design.`,
  },
  {
    img: "https://i.ibb.co/jf5QY6p/acastro-180828-1777-facebook-0001-0-0.jpg",
    title: "Multimodal Design & Social Media",
    subtitle: "Exploitation, Alienation & Hope for Something Better",
    body: `\tThis week we focused extensively on the pernicious effects of Social Media, with particular reference to Facebook. The reading, <span class="italics">Perceptions of Corporations on Facebook</span>, paid special attention to the implementation of the Beacon advertising system by the site, which exploited the user experience design of the site to improve target marketing for advertisers. Specifically the system worked by using individual interactions by users on the site to generate profiles that specified personality and value characteristics of particular users. It then used this data to determine which ads to show those users, and how to present them to said users. It is in this sense that we might say that the design of a digital media platform might be exploitative and alienating--exploiting the user experience designed for the user to alienate them from their agency and individuality.
 
    The user experience of such a digital platform is to allow the user through their freedom to engage with whoever and whatever content they find interesting and personally meaningful. Systems like Beacon then exploit this use of freedom by user on the site to reduce them into a particular profile and elicit a desired response--whether by maximizing time spent on the platform or maximizing the probability an advertisement will lead to a sale--by using means not transparent to the user and without consideration of whether this will contribute positively or negatively to the user’s well being. In this conception we might also be able to come to a normative criterion for criticism of such platforms--in whether that which they rely on for profit in the user experience they design is in harmony with the means by which they profit from user engagement. 
     
    Such systems rely on the agency and uncoerced free activity of the user to come and have a positive experience on the site by finding what they find personally meaningful. This user experience is then profited on by undermining that freedom, and ensuring future engagement less by the free activity of the user, and more by behind the scenes manipulative strategies of profiling and content curation. In this sense a system like this can be criticized for being like a mousetrap--relying for its mechanism to work on the individual to come to the platform in the free pursuit of their interests, but then keeping them there through restricting that freedom and undermining the promise of enjoyment that led them there to start with.
     
    However these systems also may provide a reason for hope. If this technology can be used for ill, then in principle, it should be able to be used for the benefit of individuals. If this same system were used transparently, and with concern to actual positive return to the user as well as the company then it could engender fantastic results. For example, if such a sophisticated system of content curation and data analytic power were designed not to maximize engagement by any means, and to the end of education--it promises to offer an education personalized to the interests of each user.`,
  },
  {
    img: "https://i.ibb.co/sgbCvxb/image5.png",
    title: "Cultural Heritage & the Blockchain",
    subtitle: "Accessibility, Comprehensibility & Economy",
    body: `\tThis week the conversation focused on potential applications of blockchain technology to cultural heritage and archival preservation. Blockchain tech is great candidate for this endeavor due to its versatility. It's in principle possible not just to store particular digital technologies in the blockchain, but also entire code architectures--which would help with the problem of obsolescence and the loss of the technology required to run older applications. While it would not eliminate the hardware problem, the blockchain could serve as a safe place to store and make publicly accessible digital software applications. Of course conventional artifacts of archival significance would also be able to be stored such as photos, videos, and texts. The technology also effectively safeguards and democratizes access to archival content--making it fully publicly available and inalterable to any person. 
 
    The major obstacle I see in the present to this project is the accessibility of blockchain technology and economic costs. The way that blockchains store, access and represent data are extremely unintuitive, and achieved through advanced cryptographic methods that are the subject of Ph.D dissertations in computer science. Furthermore, every upload to the blockchain costs money, as those processes take up bandwidth and technological resources. Furthermore, blockchain networks are decentralized and must take these resources from machines voluntarily connecting to the network to process its cued functions--many of which are owned by private citizens. The way this works is by charging ‘gas fees’ to those trying to upload and engage in transactions on blockchain networks, which are then provided to ‘miners’ who dedicate their computers to do the work of processing requests and uploads to the network. Moreover, these fees are charged for cryptocurrencies, another technology which is quite unintuitive and difficult for most people to acquire and access. 
     
    These barriers to understanding and accessibility pose a major challenge to the project of using blockchain technology as an archival resource. The hope is that as these technologies become more developed and proven over time, that the incetive will be created for large numbers of individuals to develop interfaces and inroads to using these technologies more accessible and marketable to a larger group of people. This is not an overly idealistic vision either, as this is the same course that computer technology and the internet followed--being bulky and having a high economic and personal cognitive effort cost to interact with and appealing only to a small market of tech savvy specialists at first, to its current intuitive and easy to use form. Hopefully blockchain technology will follow this same pattern of progression, and insofar as it does, this will make the chances of broad-scale integration of the technology into archival projects and institutions more likely.
    `,
  },
  {
    img: "",
    title: "What is the Digital Humanities?",
    subtitle: "Returning to the Original Question",
    body: `\tIn our final class this week we centered back on the question of what it is we were all up to in the Digital Humanities. We reflected on the fact that we were less confident that the discipline in essence was really as new as it intuitively seemed to be at first--having discussed the way the core themes and subjects of the program--even those seemingly very new such as computer code--are relevant to the earliest civilizations. I proposed that what we call the digital humanities today is less a fundamentally distinct discipline than it is a fracture in the conventional humanities caused by a lack of adaptation in the discipline to the changing contemporary technological landscape.
 
    Digital humanities scholars see the timeless questions and themes of the humanities in the contemporary technological landscape and recognize the imperative to adapt the discipline to make the most of these new technologies and ways of interacting with media, lest they get swept aside by it and lose out on the tremendous value they have to offer. At the present, the university is facing significant problems of scale--seeing higher enrollment numbers and committing itself further to ideals of inclusivity and accessibility. All the while the quality of education is at risk--as class sizes continue to increase, the unique value proposition of the university, and the greatest of the humanities university experience--a personal relationship with brilliant educated minds--is threatened. Interactive, digital technologies hold promise as a means to increase the quality of pedagogy, to connect people together and to engage people at an individual level. I see the digital humanities as an attempt to realize that promise and aide the university through this critical juncture of its history.
    `,
  },
];

export default blogs;
